# Generated by Django 3.0.2 on 2020-01-29 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10, unique=True)),
                ('soup', models.CharField(max_length=50)),
                ('main_course', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_is_warden', models.BooleanField(default=False)),
                ('person_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('person_prn', models.CharField(default='0', max_length=150, unique=True)),
                ('person_room_number', models.CharField(default='0', max_length=15, null=True)),
                ('person_is_chief', models.BooleanField(default=False)),
                ('person_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('room', 'Room'), ('wifi', 'WiFi'), ('water', 'Water'), ('other', 'Other')], max_length=10)),
                ('complaint_status', models.CharField(choices=[('reg', 'Registered'), ('ip', 'In process'), ('s', 'Solved')], max_length=10)),
                ('reg_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Person')),
            ],
        ),
    ]
