# Generated by Django 3.0.2 on 2020-01-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_is_staff', models.BooleanField(default=False)),
                ('person_first_name', models.CharField(max_length=50)),
                ('person_last_name', models.CharField(max_length=50)),
                ('person_email', models.CharField(max_length=150)),
                ('person_phone', models.IntegerField()),
                ('person_is_chief', models.BooleanField(default=False)),
                ('person_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('room', 'Room'), ('wifi', 'WiFi'), ('water', 'Water'), ('other', 'Other')], max_length=10)),
                ('complaint_status', models.CharField(choices=[('reg', 'Registered'), ('ip', 'In process'), ('s', 'Solved')], max_length=10)),
                ('reg_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Person')),
            ],
        ),
    ]
