# Generated by Django 3.0.2 on 2020-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20200127_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10, unique=True)),
                ('soup', models.CharField(max_length=50)),
                ('main_course', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=50)),
            ],
        ),
    ]
