# Generated by Django 3.0.2 on 2020-01-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_messmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
