# Generated by Django 3.0.2 on 2020-01-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20200128_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_prn',
            field=models.CharField(default='0', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_room_number',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
